repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.5.1'
    hooks:
      - id: poetry-check
      - id: poetry-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.1.4'
    hooks:
      - id: ruff
        args: [--fix]
  - repo: https://github.com/psf/black
    rev: '23.10.1'
    hooks:
      - id: black